artifacts:
  files_path: "./artifacts/files"
  train_models: "./artifacts/checkpoints/train_models"
  best_model: "./artifacts/checkpoints/best_model"

LLaMA:
  dimension: 512
  num_vocabularies: 4096
  query_heads: 8
  num_layers: 16
  kv_heads: 4
  eps: 1e-4
  sequence_length: 128
  base: 10000
  output_dimension: 14336

trainer:
  epochs: 200
  lr: 1e-5
  beta1: 0.9
  beta2: 0.999
  device: "cuda"